name: my_ollama
description: "MyOllama"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+41204

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_advanced_drawer: ^1.3.7
  sqflite: ^2.4.1
  intl: ^0.19.0
  event_bus: ^2.0.0
  flutter_chat_ui: ^1.6.15
  uuid: ^3.0.7
  ollama_dart: ^0.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  package_info_plus: ^8.1.1
  dart_ping: ^9.0.1
  url_launcher: ^6.3.1
  easy_localization: ^3.0.7
  app_settings: ^5.1.1
  flutter_styled_toast: ^2.2.1
  share_plus: ^10.1.2
  flutter_markdown: ^0.7.4+3
  split_view: ^3.2.1
  sqflite_common_ffi: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/

